/**
 * Zoo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAnimalDto { 
    /**
     * The name of the animal
     */
    name: string;
    /**
     * The species of the animal
     */
    species: string;
}

